const ADMIN_BASE = '/app/admin';
const USER_BASE = '/app/user';
const CONSULTANT_BASE = '/app/consultant';

const AdminPath = {
  DASHBOARD: `${ADMIN_BASE}/dashboard`,
  FAVOURITES: `${ADMIN_BASE}/favourites`,
  RECENT_ITEMS: `${ADMIN_BASE}/recent-items`,
  INCIDENT_MANAGEMENT: `${ADMIN_BASE}/incident-management`,
  CHANGE_MANAGEMENT: `${ADMIN_BASE}/change-management`,
  PROBLEM_MANAGEMENT: `${ADMIN_BASE}/problem-management`,
  TIME_MANAGEMENT: `${ADMIN_BASE}/time-management`,
  REPORTS: `${ADMIN_BASE}/reports`,
  TICKET_TEMPLATES: `${ADMIN_BASE}/ticket-templates`,
  CAB_REQUEST: `${ADMIN_BASE}/cab-request`,
  KNOWLEDGE_BASE: `${ADMIN_BASE}/knowledge-base`,
  TEST_SCRIPTS: `${ADMIN_BASE}/test-scripts`,
  CREATE_TICKET: `${ADMIN_BASE}/create-ticket`,
  CREATE_TICKET_TYPE: `${ADMIN_BASE}/:type`,
  CREATE_MANAGEMENT: `${ADMIN_BASE}/create-management`,
  CREATE_MANAGEMENT_TYPE: `${ADMIN_BASE}/create-management/:type`,
  CREATE_CUSTOMER: `${ADMIN_BASE}/create-customer`,
  CREATE_CUSTOMER_TYPE: `${ADMIN_BASE}/create-customer/:type`,
  USER_MANAGEMENT: `${ADMIN_BASE}/user-management`,
  ROLE_REQUESTS: `${ADMIN_BASE}/access-requests`,
  PROFILE: `${ADMIN_BASE}/profile`,
  INCIDENT_DETAIL: `${ADMIN_BASE}/incident/:number`,
  TICKET_DETAIL: `${ADMIN_BASE}/ticket/:number`,
  SUGGESTED_SOLUTION: `${ADMIN_BASE}/suggested-solution`,
  CONSULTANT_PROFILE: `${ADMIN_BASE}/consultant-profile`,
  CONFIGURATION: `${ADMIN_BASE}/configuration`,
  USER_DETAIL: `${ADMIN_BASE}/user/:id`,
  CUSTOMER_DETAIL: `${ADMIN_BASE}/customer/:id`,
  MOBILITY_ACCESS: `${ADMIN_BASE}/customer-access/mobility`,
  LOGISTICS_ACCESS: `${ADMIN_BASE}/customer-access/logistics`,
  PARCEL_ACCESS: `${ADMIN_BASE}/customer-access/parcel`,
  DRIVER_HIRE_ACCESS: `${ADMIN_BASE}/customer-access/driver-hire`,
  VEHICLE_RENTAL_ACCESS: `${ADMIN_BASE}/customer-access/vehicle-rental`,
  MECHANIC_ACCESS: `${ADMIN_BASE}/customer-access/mechanic`,
  PETROL_BUNK_ACCESS: `${ADMIN_BASE}/customer-access/petrol-bunk`,
  EV_CHARGING_ACCESS: `${ADMIN_BASE}/customer-access/ev-charging`,
  SHOWROOM_ACCESS: `${ADMIN_BASE}/customer-access/showroom`,
  VEHICLE_FINANCE_ACCESS: `${ADMIN_BASE}/customer-access/vehicle-finance`,
  FINANCE_BROKER_ACCESS: `${ADMIN_BASE}/customer-access/finance-broker`,
  INSURANCE_ACCESS: `${ADMIN_BASE}/customer-access/insurance`,
  USER_ACCESS: `${ADMIN_BASE}/customer-access/user`,
  MOBILITY_MANAGEMENT: `${ADMIN_BASE}/customer-management/mobility`,
  LOGISTICS_MANAGEMENT: `${ADMIN_BASE}/customer-management/logistics`,
  PARCEL_MANAGEMENT: `${ADMIN_BASE}/customer-management/parcel`,
  DRIVER_HIRE_MANAGEMENT: `${ADMIN_BASE}/customer-management/driver-hire`,
  VEHICLE_RENTAL_MANAGEMENT: `${ADMIN_BASE}/customer-management/vehicle-rental`,
  MECHANIC_MANAGEMENT: `${ADMIN_BASE}/customer-management/mechanic`,
  PETROL_BUNK_MANAGEMENT: `${ADMIN_BASE}/customer-management/petrol-bunk`,
  EV_CHARGING_MANAGEMENT: `${ADMIN_BASE}/customer-management/ev-charging`,
  SHOWROOM_MANAGEMENT: `${ADMIN_BASE}/customer-management/showroom`,
  VEHICLE_FINANCE_MANAGEMENT: `${ADMIN_BASE}/customer-management/vehicle-finance`,
  FINANCE_BROKER_MANAGEMENT: `${ADMIN_BASE}/customer-management/finance-broker`,
  INSURANCE_MANAGEMENT: `${ADMIN_BASE}/customer-management/insurance`,
  USER_MGMT: `${ADMIN_BASE}/customer-management/user`,
  ACCESS_MANAGEMENT: `${ADMIN_BASE}/people-management/access`,
  PEOPLE_ACCESS: `${ADMIN_BASE}/people-access`,
  PEOPLE_MANAGEMENT: `${ADMIN_BASE}/people-management`,
  TRANSACTIONS: `${ADMIN_BASE}/transactions`,
  DRIVER_EARNINGS: `${ADMIN_BASE}/driver-earnings`,
  COMMISSIONS: `${ADMIN_BASE}/commissions`,
  SUBSCRIPTIONS: `${ADMIN_BASE}/subscriptions`,
  TAGS: `${ADMIN_BASE}/tags`,
  ANALYTICS: `${ADMIN_BASE}/analytics`,
  EVENTS: `${ADMIN_BASE}/activity-logs`,
  AUDIT_TRAILS: `${ADMIN_BASE}/audit-logs`,
  SERVICES: `${ADMIN_BASE}/service-types`,
  PRICING: `${ADMIN_BASE}/pricing`,
  CATEGORIES: `${ADMIN_BASE}/categories`,
  RULES: `${ADMIN_BASE}/business-rules`,
  FEATURE_FLAGS: `${ADMIN_BASE}/feature-flags`,
  ZONES: `${ADMIN_BASE}/service-zones`,
  INTEGRATIONS: `${ADMIN_BASE}/integrations`,
};

const UserPath = {
  DASHBOARD: `${USER_BASE}/dashboard`,
  FAVOURITES: `${USER_BASE}/favourites`,
  RECENT_ITEMS: `${USER_BASE}/recent-items`,
  INCIDENT_MANAGEMENT: `${USER_BASE}/incident-management`,
  CHANGE_MANAGEMENT: `${USER_BASE}/change-management`,
  PROBLEM_MANAGEMENT: `${USER_BASE}/problem-management`,
};

const ConsultantPath = {
  DASHBOARD: `${CONSULTANT_BASE}/dashboard`,
  CHANGE_MANAGEMENT: `${CONSULTANT_BASE}/change-management`,
  PROBLEM_MANAGEMENT: `${CONSULTANT_BASE}/problem-management`,
  CREATE_TICKET: `${CONSULTANT_BASE}/create-ticket`,
  CUSTOMER_DETAIL: `${CONSULTANT_BASE}/customer/:id`,
  PEOPLE_ACCESS: `${CONSULTANT_BASE}/people-access`,
  PEOPLE_MANAGEMENT: `${CONSULTANT_BASE}/people-management`,
  MOBILITY_ACCESS: `${CONSULTANT_BASE}/customer-access/mobility`,
  LOGISTICS_ACCESS: `${CONSULTANT_BASE}/customer-access/logistics`,
  PARCEL_ACCESS: `${CONSULTANT_BASE}/customer-access/parcel`,
  DRIVER_HIRE_ACCESS: `${CONSULTANT_BASE}/customer-access/driver-hire`,
  VEHICLE_RENTAL_ACCESS: `${CONSULTANT_BASE}/customer-access/vehicle-rental`,
  MECHANIC_ACCESS: `${CONSULTANT_BASE}/customer-access/mechanic`,
  PETROL_BUNK_ACCESS: `${CONSULTANT_BASE}/customer-access/petrol-bunk`,
  EV_CHARGING_ACCESS: `${CONSULTANT_BASE}/customer-access/ev-charging`,
  SHOWROOM_ACCESS: `${CONSULTANT_BASE}/customer-access/showroom`,
  VEHICLE_FINANCE_ACCESS: `${CONSULTANT_BASE}/customer-access/vehicle-finance`,
  FINANCE_BROKER_ACCESS: `${CONSULTANT_BASE}/customer-access/finance-broker`,
  INSURANCE_ACCESS: `${CONSULTANT_BASE}/customer-access/insurance`,
  USER_ACCESS: `${CONSULTANT_BASE}/customer-access/user`,
  MOBILITY_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/mobility`,
  LOGISTICS_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/logistics`,
  PARCEL_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/parcel`,
  DRIVER_HIRE_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/driver-hire`,
  VEHICLE_RENTAL_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/vehicle-rental`,
  MECHANIC_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/mechanic`,
  PETROL_BUNK_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/petrol-bunk`,
  EV_CHARGING_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/ev-charging`,
  SHOWROOM_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/showroom`,
  VEHICLE_FINANCE_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/vehicle-finance`,
  FINANCE_BROKER_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/finance-broker`,
  INSURANCE_MANAGEMENT: `${CONSULTANT_BASE}/customer-management/insurance`,
  USER_MGMT: `${CONSULTANT_BASE}/customer-management/user`,
};

const AuthPath = {
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
};

const DefalutPage = {
  ADMIN_DEFAULT_PAGE: '/app/admin/*',
  USER_DEFAULT_PAGE: '/app/user/*',
  CONSULTANT_DEFAULT_PAGE: '/app/consultant/*',
};

/**
 * Combined Path object.
 * - Admin components should use constants.AdminPath
 * - User components should use constants.UserPath
 * - Auth/shared components should use constants.Path for auth routes
 */
const Path = {
  DEFAULT_PAGE: '/',
  ...AuthPath,
  ...AdminPath,
  NOT_FOUND: '*',
};

export const constants = {
  Path,
  AdminPath,
  UserPath,
  ConsultantPath,
  AuthPath,
  ADMIN_BASE,
  USER_BASE,
  CONSULTANT_BASE,
  DefalutPage,
};
