export interface TurbineData {
  id: number;
  turbineNo: string;
  status: 'running' | 'stopped' | 'maintenance' | 'fault' | 'standby';
  time: string;

  // Core Performance
  activePower: number; // kW
  windSpeed: number; // m/s
  breakProgramme: string; // Released / Applied / Emergency
  operatingMode: string;
  todayGeneration: number; // kWh
  totalProduction: number; // MWh
  totalOperatingHours: number; // h
  totalProductionHours: number; // h
  operationHoursToday: number; // h

  // Electrical — MFR300
  currentL1: number; // A
  currentL2: number; // A
  currentL3: number; // A
  powerFrequency: number; // Hz
  voltageL1: number; // V
  voltageL2: number; // V
  voltageL3: number; // V
  apparentPower: number; // kVA
  reactivePower: number; // kVAR
  powerFactor: number; // –

  // Drive Train & Rotor
  rotorRpm: number; // rpm
  gearSpeed: number; // rpm
  generatorRpm: number; // rpm
  nacellePosition: number; // °
  cableWinding: number; // °
  windDirection: number; // °
  relativeWindDirection: number; // °
  pitchAngle: number; // ° (blade angle)
  pitchCylinder1: number; // mm
  pitchCylinder2: number; // mm
  pitchCylinder3: number; // mm

  // Structural Monitoring
  towerOscillationX: number; // mm/s
  towerOscillationY: number; // mm/s

  // Temperature Monitoring
  outdoorTemp: number; // °C
  trfWindingTempU: number; // °C
  trfWindingTempV: number; // °C
  trfWindingTempW: number; // °C
  nacelleTemp: number; // °C
  coolCnvHeatExIn: number; // °C
  coolCnvHeatExOut: number; // °C
  coolTrfHeatExIn: number; // °C
  gearOilSumpTemp: number; // °C
  generatorWindingTempU: number; // °C
  generatorWindingTempV: number; // °C
  generatorWindingTempW: number; // °C
  gearboxTemp: number; // °C
  generatorTemp: number; // °C
  transformerTemp: number; // °C
  hubExhaustTemp: number; // °C

  // Pressure & Hydraulics
  hydraulicPressure: number; // bar
  gearOilPressure: number; // bar
  coolantInletPressure: number; // bar
  coolantOutletPressure: number; // bar

  // Control Cabinet Temperatures
  tempSwCabTower: number; // °C
  tempSwCabNacelle: number; // °C
  tempSwCabHub: number; // °C
}

export const STATUS_CONFIG = {
  running: {
    label: 'Running',
    color: '#10b981',
    bgColor: 'rgba(16, 185, 129, 0.12)',
    borderColor: 'rgba(16, 185, 129, 0.4)',
  },
  stopped: {
    label: 'Stopped',
    color: '#6b7280',
    bgColor: 'rgba(107, 114, 128, 0.12)',
    borderColor: 'rgba(107, 114, 128, 0.4)',
  },
  maintenance: {
    label: 'Maintenance',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.12)',
    borderColor: 'rgba(245, 158, 11, 0.4)',
  },
  fault: {
    label: 'Fault',
    color: '#ef4444',
    bgColor: 'rgba(239, 68, 68, 0.12)',
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  standby: {
    label: 'Standby',
    color: '#3b82f6',
    bgColor: 'rgba(59, 130, 246, 0.12)',
    borderColor: 'rgba(59, 130, 246, 0.4)',
  },
};

export const MOCK_TURBINE_DATA: TurbineData[] = [
  {
    id: 1,
    turbineNo: 'T-01',
    status: 'running',
    time: '14:32:15',
    activePower: 1850,
    windSpeed: 8.5,
    breakProgramme: 'Released',
    operatingMode: 'Grid Connected',
    todayGeneration: 4285,
    totalProduction: 12450,
    totalOperatingHours: 14820,
    totalProductionHours: 13540,
    operationHoursToday: 11.2,
    currentL1: 1542,
    currentL2: 1538,
    currentL3: 1545,
    powerFrequency: 50.01,
    voltageL1: 691,
    voltageL2: 689,
    voltageL3: 690,
    apparentPower: 1948,
    reactivePower: 485,
    powerFactor: 0.95,
    rotorRpm: 14.2,
    gearSpeed: 248,
    generatorRpm: 1520,
    nacellePosition: 242,
    cableWinding: 125,
    windDirection: 245,
    relativeWindDirection: -3,
    pitchAngle: 3.2,
    pitchCylinder1: 142,
    pitchCylinder2: 144,
    pitchCylinder3: 141,
    towerOscillationX: 0.18,
    towerOscillationY: 0.12,
    outdoorTemp: 28,
    trfWindingTempU: 68,
    trfWindingTempV: 70,
    trfWindingTempW: 67,
    nacelleTemp: 38,
    coolCnvHeatExIn: 52,
    coolCnvHeatExOut: 32,
    coolTrfHeatExIn: 48,
    gearOilSumpTemp: 62,
    generatorWindingTempU: 82,
    generatorWindingTempV: 84,
    generatorWindingTempW: 81,
    gearboxTemp: 52,
    generatorTemp: 65,
    transformerTemp: 42,
    hubExhaustTemp: 38,
    hydraulicPressure: 185,
    gearOilPressure: 3.1,
    coolantInletPressure: 1.8,
    coolantOutletPressure: 1.3,
    tempSwCabTower: 32,
    tempSwCabNacelle: 36,
    tempSwCabHub: 34,
  },
  {
    id: 2,
    turbineNo: 'T-02',
    status: 'running',
    time: '14:32:18',
    activePower: 1920,
    windSpeed: 9.2,
    breakProgramme: 'Released',
    operatingMode: 'Grid Connected',
    todayGeneration: 4510,
    totalProduction: 11820,
    totalOperatingHours: 14210,
    totalProductionHours: 13020,
    operationHoursToday: 11.8,
    currentL1: 1600,
    currentL2: 1596,
    currentL3: 1602,
    powerFrequency: 49.98,
    voltageL1: 692,
    voltageL2: 690,
    voltageL3: 691,
    apparentPower: 2021,
    reactivePower: 510,
    powerFactor: 0.95,
    rotorRpm: 14.8,
    gearSpeed: 258,
    generatorRpm: 1580,
    nacellePosition: 240,
    cableWinding: 148,
    windDirection: 238,
    relativeWindDirection: -2,
    pitchAngle: 2.8,
    pitchCylinder1: 148,
    pitchCylinder2: 146,
    pitchCylinder3: 147,
    towerOscillationX: 0.22,
    towerOscillationY: 0.15,
    outdoorTemp: 27,
    trfWindingTempU: 71,
    trfWindingTempV: 73,
    trfWindingTempW: 70,
    nacelleTemp: 40,
    coolCnvHeatExIn: 55,
    coolCnvHeatExOut: 34,
    coolTrfHeatExIn: 50,
    gearOilSumpTemp: 65,
    generatorWindingTempU: 86,
    generatorWindingTempV: 88,
    generatorWindingTempW: 85,
    gearboxTemp: 54,
    generatorTemp: 68,
    transformerTemp: 44,
    hubExhaustTemp: 40,
    hydraulicPressure: 188,
    gearOilPressure: 3.2,
    coolantInletPressure: 1.9,
    coolantOutletPressure: 1.4,
    tempSwCabTower: 33,
    tempSwCabNacelle: 38,
    tempSwCabHub: 35,
  },
  {
    id: 3,
    turbineNo: 'T-03',
    status: 'maintenance',
    time: '14:30:00',
    activePower: 0,
    windSpeed: 7.1,
    breakProgramme: 'Applied',
    operatingMode: 'Service Mode',
    todayGeneration: 3892,
    totalProduction: 9870,
    totalOperatingHours: 12400,
    totalProductionHours: 11200,
    operationHoursToday: 6.5,
    currentL1: 0,
    currentL2: 0,
    currentL3: 0,
    powerFrequency: 0,
    voltageL1: 0,
    voltageL2: 0,
    voltageL3: 0,
    apparentPower: 0,
    reactivePower: 0,
    powerFactor: 0,
    rotorRpm: 0,
    gearSpeed: 0,
    generatorRpm: 0,
    nacellePosition: 180,
    cableWinding: 82,
    windDirection: 260,
    relativeWindDirection: 80,
    pitchAngle: 90,
    pitchCylinder1: 285,
    pitchCylinder2: 285,
    pitchCylinder3: 285,
    towerOscillationX: 0.02,
    towerOscillationY: 0.01,
    outdoorTemp: 29,
    trfWindingTempU: 38,
    trfWindingTempV: 38,
    trfWindingTempW: 37,
    nacelleTemp: 32,
    coolCnvHeatExIn: 30,
    coolCnvHeatExOut: 25,
    coolTrfHeatExIn: 29,
    gearOilSumpTemp: 38,
    generatorWindingTempU: 35,
    generatorWindingTempV: 36,
    generatorWindingTempW: 35,
    gearboxTemp: 35,
    generatorTemp: 32,
    transformerTemp: 38,
    hubExhaustTemp: 28,
    hydraulicPressure: 175,
    gearOilPressure: 2.8,
    coolantInletPressure: 1.2,
    coolantOutletPressure: 0.9,
    tempSwCabTower: 29,
    tempSwCabNacelle: 31,
    tempSwCabHub: 28,
  },
  {
    id: 4,
    turbineNo: 'T-04',
    status: 'running',
    time: '14:32:22',
    activePower: 1650,
    windSpeed: 7.8,
    breakProgramme: 'Released',
    operatingMode: 'Grid Connected',
    todayGeneration: 3950,
    totalProduction: 10920,
    totalOperatingHours: 13650,
    totalProductionHours: 12480,
    operationHoursToday: 10.8,
    currentL1: 1375,
    currentL2: 1371,
    currentL3: 1378,
    powerFrequency: 50.02,
    voltageL1: 690,
    voltageL2: 691,
    voltageL3: 689,
    apparentPower: 1737,
    reactivePower: 432,
    powerFactor: 0.95,
    rotorRpm: 13.1,
    gearSpeed: 228,
    generatorRpm: 1420,
    nacellePosition: 255,
    cableWinding: 162,
    windDirection: 252,
    relativeWindDirection: 3,
    pitchAngle: 4.1,
    pitchCylinder1: 135,
    pitchCylinder2: 138,
    pitchCylinder3: 136,
    towerOscillationX: 0.14,
    towerOscillationY: 0.1,
    outdoorTemp: 28,
    trfWindingTempU: 64,
    trfWindingTempV: 66,
    trfWindingTempW: 63,
    nacelleTemp: 36,
    coolCnvHeatExIn: 49,
    coolCnvHeatExOut: 30,
    coolTrfHeatExIn: 45,
    gearOilSumpTemp: 59,
    generatorWindingTempU: 78,
    generatorWindingTempV: 80,
    generatorWindingTempW: 77,
    gearboxTemp: 50,
    generatorTemp: 62,
    transformerTemp: 40,
    hubExhaustTemp: 36,
    hydraulicPressure: 182,
    gearOilPressure: 3.0,
    coolantInletPressure: 1.7,
    coolantOutletPressure: 1.2,
    tempSwCabTower: 31,
    tempSwCabNacelle: 35,
    tempSwCabHub: 33,
  },
  {
    id: 5,
    turbineNo: 'T-05',
    status: 'fault',
    time: '14:25:45',
    activePower: 0,
    windSpeed: 6.5,
    breakProgramme: 'Emergency',
    operatingMode: 'Fault Stop',
    todayGeneration: 3125,
    totalProduction: 8540,
    totalOperatingHours: 11200,
    totalProductionHours: 10100,
    operationHoursToday: 4.2,
    currentL1: 0,
    currentL2: 0,
    currentL3: 0,
    powerFrequency: 0,
    voltageL1: 0,
    voltageL2: 0,
    voltageL3: 0,
    apparentPower: 0,
    reactivePower: 0,
    powerFactor: 0,
    rotorRpm: 0,
    gearSpeed: 0,
    generatorRpm: 0,
    nacellePosition: 290,
    cableWinding: 210,
    windDirection: 275,
    relativeWindDirection: -15,
    pitchAngle: 0,
    pitchCylinder1: 0,
    pitchCylinder2: 0,
    pitchCylinder3: 0,
    towerOscillationX: 0.04,
    towerOscillationY: 0.03,
    outdoorTemp: 30,
    trfWindingTempU: 44,
    trfWindingTempV: 45,
    trfWindingTempW: 43,
    nacelleTemp: 35,
    coolCnvHeatExIn: 35,
    coolCnvHeatExOut: 27,
    coolTrfHeatExIn: 33,
    gearOilSumpTemp: 45,
    generatorWindingTempU: 55,
    generatorWindingTempV: 56,
    generatorWindingTempW: 54,
    gearboxTemp: 45,
    generatorTemp: 55,
    transformerTemp: 42,
    hubExhaustTemp: 32,
    hydraulicPressure: 160,
    gearOilPressure: 2.5,
    coolantInletPressure: 1.0,
    coolantOutletPressure: 0.7,
    tempSwCabTower: 30,
    tempSwCabNacelle: 33,
    tempSwCabHub: 31,
  },
  {
    id: 6,
    turbineNo: 'T-06',
    status: 'running',
    time: '14:32:28',
    activePower: 1780,
    windSpeed: 8.1,
    breakProgramme: 'Released',
    operatingMode: 'Grid Connected',
    todayGeneration: 4120,
    totalProduction: 11280,
    totalOperatingHours: 13900,
    totalProductionHours: 12750,
    operationHoursToday: 11.5,
    currentL1: 1484,
    currentL2: 1480,
    currentL3: 1487,
    powerFrequency: 50.0,
    voltageL1: 691,
    voltageL2: 690,
    voltageL3: 690,
    apparentPower: 1874,
    reactivePower: 468,
    powerFactor: 0.95,
    rotorRpm: 13.8,
    gearSpeed: 241,
    generatorRpm: 1490,
    nacellePosition: 248,
    cableWinding: 138,
    windDirection: 248,
    relativeWindDirection: 0,
    pitchAngle: 3.5,
    pitchCylinder1: 139,
    pitchCylinder2: 142,
    pitchCylinder3: 140,
    towerOscillationX: 0.16,
    towerOscillationY: 0.11,
    outdoorTemp: 27,
    trfWindingTempU: 66,
    trfWindingTempV: 68,
    trfWindingTempW: 65,
    nacelleTemp: 39,
    coolCnvHeatExIn: 51,
    coolCnvHeatExOut: 31,
    coolTrfHeatExIn: 47,
    gearOilSumpTemp: 61,
    generatorWindingTempU: 80,
    generatorWindingTempV: 82,
    generatorWindingTempW: 79,
    gearboxTemp: 51,
    generatorTemp: 64,
    transformerTemp: 41,
    hubExhaustTemp: 37,
    hydraulicPressure: 184,
    gearOilPressure: 3.1,
    coolantInletPressure: 1.8,
    coolantOutletPressure: 1.3,
    tempSwCabTower: 32,
    tempSwCabNacelle: 37,
    tempSwCabHub: 34,
  },
  {
    id: 7,
    turbineNo: 'T-07',
    status: 'standby',
    time: '14:32:00',
    activePower: 120,
    windSpeed: 4.2,
    breakProgramme: 'Released',
    operatingMode: 'Low Wind Standby',
    todayGeneration: 2890,
    totalProduction: 7620,
    totalOperatingHours: 10800,
    totalProductionHours: 9700,
    operationHoursToday: 8.1,
    currentL1: 100,
    currentL2: 98,
    currentL3: 101,
    powerFrequency: 50.0,
    voltageL1: 690,
    voltageL2: 689,
    voltageL3: 691,
    apparentPower: 126,
    reactivePower: 32,
    powerFactor: 0.95,
    rotorRpm: 2.1,
    gearSpeed: 36,
    generatorRpm: 220,
    nacellePosition: 305,
    cableWinding: 188,
    windDirection: 310,
    relativeWindDirection: 5,
    pitchAngle: 85,
    pitchCylinder1: 268,
    pitchCylinder2: 270,
    pitchCylinder3: 269,
    towerOscillationX: 0.06,
    towerOscillationY: 0.04,
    outdoorTemp: 31,
    trfWindingTempU: 42,
    trfWindingTempV: 43,
    trfWindingTempW: 41,
    nacelleTemp: 33,
    coolCnvHeatExIn: 36,
    coolCnvHeatExOut: 27,
    coolTrfHeatExIn: 34,
    gearOilSumpTemp: 41,
    generatorWindingTempU: 38,
    generatorWindingTempV: 39,
    generatorWindingTempW: 38,
    gearboxTemp: 38,
    generatorTemp: 35,
    transformerTemp: 36,
    hubExhaustTemp: 30,
    hydraulicPressure: 178,
    gearOilPressure: 2.9,
    coolantInletPressure: 1.5,
    coolantOutletPressure: 1.1,
    tempSwCabTower: 31,
    tempSwCabNacelle: 34,
    tempSwCabHub: 32,
  },
  {
    id: 8,
    turbineNo: 'T-08',
    status: 'running',
    time: '14:32:35',
    activePower: 1950,
    windSpeed: 9.8,
    breakProgramme: 'Released',
    operatingMode: 'Grid Connected',
    todayGeneration: 4680,
    totalProduction: 13200,
    totalOperatingHours: 15400,
    totalProductionHours: 14100,
    operationHoursToday: 12.1,
    currentL1: 1625,
    currentL2: 1621,
    currentL3: 1628,
    powerFrequency: 49.99,
    voltageL1: 692,
    voltageL2: 691,
    voltageL3: 690,
    apparentPower: 2053,
    reactivePower: 519,
    powerFactor: 0.95,
    rotorRpm: 15.2,
    gearSpeed: 265,
    generatorRpm: 1620,
    nacellePosition: 238,
    cableWinding: 112,
    windDirection: 235,
    relativeWindDirection: -3,
    pitchAngle: 2.5,
    pitchCylinder1: 152,
    pitchCylinder2: 149,
    pitchCylinder3: 151,
    towerOscillationX: 0.26,
    towerOscillationY: 0.18,
    outdoorTemp: 26,
    trfWindingTempU: 73,
    trfWindingTempV: 75,
    trfWindingTempW: 72,
    nacelleTemp: 42,
    coolCnvHeatExIn: 57,
    coolCnvHeatExOut: 36,
    coolTrfHeatExIn: 52,
    gearOilSumpTemp: 68,
    generatorWindingTempU: 88,
    generatorWindingTempV: 90,
    generatorWindingTempW: 87,
    gearboxTemp: 56,
    generatorTemp: 70,
    transformerTemp: 45,
    hubExhaustTemp: 42,
    hydraulicPressure: 190,
    gearOilPressure: 3.3,
    coolantInletPressure: 1.9,
    coolantOutletPressure: 1.4,
    tempSwCabTower: 34,
    tempSwCabNacelle: 39,
    tempSwCabHub: 36,
  },
  {
    id: 9,
    turbineNo: 'T-09',
    status: 'stopped',
    time: '14:20:00',
    activePower: 0,
    windSpeed: 10.5,
    breakProgramme: 'Applied',
    operatingMode: 'Manual Stop',
    todayGeneration: 3850,
    totalProduction: 10100,
    totalOperatingHours: 12800,
    totalProductionHours: 11600,
    operationHoursToday: 5.0,
    currentL1: 0,
    currentL2: 0,
    currentL3: 0,
    powerFrequency: 0,
    voltageL1: 0,
    voltageL2: 0,
    voltageL3: 0,
    apparentPower: 0,
    reactivePower: 0,
    powerFactor: 0,
    rotorRpm: 0,
    gearSpeed: 0,
    generatorRpm: 0,
    nacellePosition: 220,
    cableWinding: 95,
    windDirection: 225,
    relativeWindDirection: -5,
    pitchAngle: 90,
    pitchCylinder1: 285,
    pitchCylinder2: 285,
    pitchCylinder3: 285,
    towerOscillationX: 0.03,
    towerOscillationY: 0.02,
    outdoorTemp: 25,
    trfWindingTempU: 36,
    trfWindingTempV: 37,
    trfWindingTempW: 36,
    nacelleTemp: 28,
    coolCnvHeatExIn: 27,
    coolCnvHeatExOut: 24,
    coolTrfHeatExIn: 26,
    gearOilSumpTemp: 35,
    generatorWindingTempU: 30,
    generatorWindingTempV: 31,
    generatorWindingTempW: 30,
    gearboxTemp: 32,
    generatorTemp: 28,
    transformerTemp: 35,
    hubExhaustTemp: 25,
    hydraulicPressure: 170,
    gearOilPressure: 2.7,
    coolantInletPressure: 1.1,
    coolantOutletPressure: 0.8,
    tempSwCabTower: 25,
    tempSwCabNacelle: 28,
    tempSwCabHub: 26,
  },
  {
    id: 10,
    turbineNo: 'T-10',
    status: 'running',
    time: '14:32:42',
    activePower: 1720,
    windSpeed: 8.0,
    breakProgramme: 'Released',
    operatingMode: 'Grid Connected',
    todayGeneration: 4055,
    totalProduction: 11650,
    totalOperatingHours: 14050,
    totalProductionHours: 12880,
    operationHoursToday: 11.0,
    currentL1: 1434,
    currentL2: 1430,
    currentL3: 1437,
    powerFrequency: 50.01,
    voltageL1: 690,
    voltageL2: 691,
    voltageL3: 690,
    apparentPower: 1811,
    reactivePower: 451,
    powerFactor: 0.95,
    rotorRpm: 13.5,
    gearSpeed: 235,
    generatorRpm: 1460,
    nacellePosition: 258,
    cableWinding: 152,
    windDirection: 255,
    relativeWindDirection: 3,
    pitchAngle: 3.8,
    pitchCylinder1: 137,
    pitchCylinder2: 140,
    pitchCylinder3: 138,
    towerOscillationX: 0.15,
    towerOscillationY: 0.1,
    outdoorTemp: 28,
    trfWindingTempU: 65,
    trfWindingTempV: 67,
    trfWindingTempW: 64,
    nacelleTemp: 37,
    coolCnvHeatExIn: 50,
    coolCnvHeatExOut: 31,
    coolTrfHeatExIn: 46,
    gearOilSumpTemp: 60,
    generatorWindingTempU: 79,
    generatorWindingTempV: 81,
    generatorWindingTempW: 78,
    gearboxTemp: 52,
    generatorTemp: 63,
    transformerTemp: 42,
    hubExhaustTemp: 38,
    hydraulicPressure: 183,
    gearOilPressure: 3.0,
    coolantInletPressure: 1.7,
    coolantOutletPressure: 1.2,
    tempSwCabTower: 31,
    tempSwCabNacelle: 36,
    tempSwCabHub: 33,
  },
];
